In [1]:
import pandas as pd

In [2]:
dict_data = {
    "c0": [1, 2, 3], 
    "c1": [4, 5, 6], 
    "c2": [7, 8, 9], 
    "c3": [10, 11, 12], 
    "c4": [13, 14, 15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [3]:
# pandas.DataFrame(2차원배열, 
#                  index=행 인덱스 배열,
#                  columns=열 이름 배열
#                  )

arr = [
    [15, "남", "덕영중"], 
    [17, "여", "수리중"]
]

df = pd.DataFrame(arr, index=["준서", "예은"], columns=["나이", "성별", "학교"])

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [7]:
print(list(df.index))
print(list(df.columns))

['준서', '예은']
['나이', '성별', '학교']

In [8]:
# 행 인덱스 변경
# DataFrame객체.index = 행인덱스배열
# DataFrame객체.columns = 열인덱스배열

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [9]:
df.index = ["학생1", "학생2"]
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [10]:
df.columns = ["연령", "남녀", "소속"]
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [11]:
# 행인덱스변경 : DataFrame객체.rename(index={기존인덱스: 새인덱스})
# 열이름변경 : DataFrame객체.rename(columns={기존이름: 새이름})

import pandas as pd

matrix = [
    [15, "남", "덕영중"], 
    [17, "여", "수리중"]
]

df = pd.DataFrame(matrix, index=["준서", "예은"], columns=["나이", "성별", "학교"])
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [14]:
df = df.rename(columns={
    "나이": "연령", 
    "성별": "남녀", 
    "학교": "소속"
})
df

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [15]:
df  =df.rename(index={
    "준서": "학생1", 
    "예은": "학생2"
})
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [17]:
# 행/열 삭제 
# 행삭제 : DataFrame객체.drop(행인덱스 또는 배열, axis=0, axis="index")
# 열삭제 : DataFrame객체.drop(열이름 또는 배열, axis=1, axis="columns")

import pandas as pd 

exam_data = {
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [85, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data, index=["서준", "우현", "민아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [18]:
df2 = df.copy()
df2 = df2.drop("우현")
df2

    수학  영어   음악   체육
서준  90  98   85  100
민아  70  95  100   90

In [ ]:
df3 = df.copy()
print(df3)
df3 = df.drop(["우현", "민아"], axis=0)
print(df3)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90
    수학  영어  음악   체육
서준  90  98  85  100

In [22]:
df4 = df.copy()
df4 = df4.drop(["우현", "민아"], axis="index")
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [23]:
df5 = df.copy()
df5 = df5.drop(index=["우현"])
df5

    수학  영어   음악   체육
서준  90  98   85  100
민아  70  95  100   90

In [26]:
import pandas as pd 

exam_data = {
    "수학": (90, 80, 70), 
    "영어": (98, 89, 95), 
    "음악": (85, 95, 100), 
    "체육": (100, 90, 90)
}

df = pd.DataFrame(exam_data, index=["서준", "우현", "민아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [25]:
df2 = df.copy()
df2 = df2.drop("수학", axis=1)
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
민아  95  100   90

In [28]:
df3 = df.copy()
df3 = df3.drop(["영어", "음악"], axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
민아  70   90

In [29]:
df4 = df.copy()
df4 = df4.drop({"영어", "음악"}, axis="columns")
df4

    수학   체육
서준  90  100
우현  80   90
민아  70   90

In [30]:
df5=df.copy()
df5 = df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
민아  95  100   90

In [31]:
# 행선택

import pandas as pd 

exam_data = {
    "수학": (90, 80, 70), 
    "영어": (98, 89, 95), 
    "음악": (85, 95, 100), 
    "체육": (100, 90, 90)
}

df = pd.DataFrame(exam_data, index=["서준", "우현", "민아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [33]:
label1 = df.loc["서준"]
print(label1)
print(type(label1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.core.series.Series'>

In [35]:
position1 = df.iloc[0]
print(position1)
print(type(position1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.core.series.Series'>

In [36]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [37]:
label2 = df.loc[["서준", "우현"]]
print(label2)
print(type(label2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.core.frame.DataFrame'>

In [38]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [39]:
label3 = df.loc[["서준"]]
print(label3)
print(type(label3))

    수학  영어  음악   체육
서준  90  98  85  100
<class 'pandas.core.frame.DataFrame'>

In [40]:
position2 = df.iloc[[0, 1]]
print(position2)
print(type(position2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.core.frame.DataFrame'>

In [41]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [ ]:
label3 = df.loc["서준":"민아"]
print(label3)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [43]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [44]:
position3 = df.iloc[0:2]
position3

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [54]:
# 열1개선택: DataFrame객체["열이름"] 또는 데이터 프레임객체.열이름

exam_data = {
    "이름": ["서준", "우현", "민아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [85, 95, 100], 
    "체육": [100, 90, 90]
}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [48]:
math1=df["수학"]
type(math1)

pandas.core.series.Series

In [52]:
english = df.영어
english

AttributeError: 'DataFrame' object has no attribute '영어'

In [53]:
df["영 어"]

0    98
1    89
2    95
Name: 영 어, dtype: int64

In [55]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [57]:
music_gym = df[["음악", "체육"]]
music_gym

    음악   체육
0   85  100
1   95   90
2  100   90

In [60]:
df1 = df["수학"]
df1.shape

(3,)

In [61]:
df2 = df[["수학"]]
df2.shape

(3, 1)

In [62]:
# 범위슬라이싱: DataFrame객체.iloc[시작인덱스:끝인덱스:간격]

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [64]:
df.iloc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  민아  70  95  100   90

In [65]:
# 원소 선택
# 인덱스이름: DataFrame객체.loc[행인덱스, 열이름]
# 정수위치인덱스: DataFrame객체.iloc[행번호, 열번호]

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [68]:
df = df.set_index("이름")

In [69]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [74]:
a =df.loc["서준", "음악"]
df.iloc[0, 2]

np.int64(85)

In [75]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [76]:
df.loc["서준", ["음악", "체육"]]

음악     85
체육    100
Name: 서준, dtype: int64

In [77]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [78]:
df.iloc[0, [2, 3]]

음악     85
체육    100
Name: 서준, dtype: int64

In [79]:
df.loc["서준", "음악":"체육"]

음악     85
체육    100
Name: 서준, dtype: int64

In [80]:
df.iloc[0, 2:]

음악     85
체육    100
Name: 서준, dtype: int64

In [81]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [83]:
df.loc[["서준", "우현"], ["음악", "체육"]]

    음악   체육
이름
서준  85  100
우현  95   90

In [85]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [87]:
df.iloc[[0, 1], [2, 3]]

    음악   체육
이름
서준  85  100
우현  95   90

In [88]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [90]:
df.loc["서준":"우현", "음악":"체육"]

    음악   체육
이름
서준  85  100
우현  95   90

In [91]:
df.iloc[0:2, 2:]

    음악   체육
이름
서준  85  100
우현  95   90

In [92]:
# 열추가 
# 열추가: DataFrame객체["추가하려는 열 이름"] = 데이터 값

df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [93]:
exam_data = {
    "이름": ["서준", "우현", "민아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [85, 95, 100], 
    "체육": [100, 90, 90]
}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [96]:
df["국어"] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  민아  70  95  100   90  80

In [98]:
df["미술"] = [80, 90, 100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  민아  70  95  100   90  80  100

In [99]:
# 행추가
# 행추가: DataFrame객체.loc["새로운해이름"] = 데이터값 또는 배열

exam_data = {
    "이름": ["서준", "우현", "민아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [85, 95, 100], 
    "체육": [100, 90, 90]
}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [102]:
print(df.loc[0:2])
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90
   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [103]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [104]:
df.loc[3] = 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90
3   0   0   0    0    0

In [105]:
df.loc[4] = ["동규", 90, 80, 70, 60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [106]:
df.loc["행5"] = df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   민아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [107]:
# 원소 값 변경

import pandas as pd

exam_data = {
    "이름": ["서준", "우현", "민아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [85, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [108]:
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [114]:
df.iloc[0, 3] = 80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
민아  70  95  100  90

In [121]:
df.loc["서준", "체육"] = 90

In [122]:
df

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
민아  70  95  100  90

In [ ]:
df.loc["서준", ["음악", "체육"]] = 90
df

    수학  영어   음악  체육
이름
서준  90  98   90  90
우현  80  89   95  90
민아  70  95  100  90

In [ ]:
df.loc["서준", ["음악", "체육"]] = [100, 50]
df

    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
민아  70  95  100  90

In [127]:
# 행 열의 위치 바꾸기 

# 행, 열 바꾸기 : DataFrame객체.transpose() 또는 T
import pandas as pd

exam_data = {
    "이름": ["서준", "우현", "민아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [85, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [128]:
df = df.transpose()
df

      0   1    2
이름   서준  우현   민아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [129]:
df = df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90