In [1]:
import pandas as pd

In [2]:
dict_data = {
    "국어": 100, 
    "영어": 80, 
    "수학": 90
}

student1 = pd.Series(dict_data)
student1

국어    100
영어     80
수학     90
dtype: int64

In [3]:
percentage = student1 / 200
print(percentage)
print(type(percentage))

국어    0.50
영어    0.40
수학    0.45
dtype: float64
<class 'pandas.core.series.Series'>

In [4]:
student1 = pd.Series({
    "국어": 100, 
    "영어": 80, 
    "수학": 90
})
student2 = pd.Series({
    "수학": 80,
    "국어": 90, 
    "영어": 80, 
})

print(student1)
print(student2)

국어    100
영어     80
수학     90
dtype: int64
수학    80
국어    90
영어    80
dtype: int64

In [5]:
print(student1 + student2)
print(type(student1 + student2))

국어    190
수학    170
영어    160
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
student1 - student2

국어    10
수학    10
영어     0
dtype: int64

In [7]:
student1 * student2

국어    9000
수학    7200
영어    6400
dtype: int64

In [8]:
student1 / student2

국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [9]:
# NaN값이 있는 시리즈 연산

import pandas as pd 
import numpy as np 

student1 = pd.Series({"국어": np.nan, "영어": 80, "수학":90})
student2 = pd.Series({"수학": 80, "국어": 90})

print(student1)
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64

In [11]:
add = student1 + student2 
sub = student1 - student2 
mul = student1 * student2 
div = student1 / student2 

print(add)
print(sub)
print(mul)
print(div)

국어      NaN
수학    170.0
영어      NaN
dtype: float64
국어     NaN
수학    10.0
영어     NaN
dtype: float64
국어       NaN
수학    7200.0
영어       NaN
dtype: float64
국어      NaN
수학    1.125
영어      NaN
dtype: float64

In [12]:
result = pd.DataFrame([
    add, 
    sub, 
    mul, 
    div
], index=["덧셈", "뺄셈", "곱셈", "나눗셈"])

result

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [17]:
# 연산메서드 
sr_add2 = student1.add(student2)
sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

# print(sr_add2)
# print(sr_add)

result = pd.DataFrame([
    sr_add, 
    sr_sub, 
    sr_mul, 
    sr_div
])

result

     국어        수학    영어
0  90.0   170.000  80.0
1 -90.0    10.000  80.0
2   0.0  7200.000   0.0
3   0.0     1.125   inf

In [19]:
# 데이터프레임 연산
import seaborn as sns

In [22]:
titanic = sns.load_dataset("titanic")

df = titanic.loc[:, ["age", "fare"]]
df

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [23]:
df.shape

(891, 2)

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
addition = df + 10
addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [26]:
# 데이터프레임 vs 데이터프레임

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df = titanic.loc[:,["age", "fare"]]

df.tail()

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75

In [27]:
addition = df + 10
addition.tail()

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [28]:
substraction = addition - df
substraction.tail()

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

In [32]:
sample1 = addition.tail()
sample2 = substraction.tail().fillna(0.0)
sample2

      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [35]:
df_add = sample1.add(sample2, fill_value=0)
df_sub = sample1.sub(sample2, fill_value=0)
df_mul = sample1.mul(sample2, fill_value=0)
df_div = sample1.div(sample2, fill_value=0)